config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'home#show'

  devise_for :users

  post 'artists/import', to: 'imports#artist'

  resources :artists do
    resources :releases do
      collection do
        post :import, to: 'imports#artist_releases'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :user
  has_many :releases
end

app/models/release.rb
class Release < ApplicationRecord
  belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :artists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def test
    puts 'test'
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = current_user.artists
  end

  def show
    render :show
  end

  def new
    @artist = Artist.new
  end

  def edit
    render :edit
  end

  def create
    @artist = Artist.new(artist_params)
    @artist.user = current_user

    if @artist.save
      redirect_to @artist, notice: 'Artist was successfully created.'
    else
      render :new
    end
  end

  def update
    if artist.update(artist_params)
      redirect_to artist, notice: 'Artist was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    artist.destroy

    redirect_to artists_url, notice: 'Artist was successfully destroyed.'
  end

  private

  def artist
    @artist ||= Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(
      :name,
      :profile
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def show
    render 'show'
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def artist
    if import_artist_params[:name].blank?
      redirect_to artists_path, notice: 'Please inform an artist'

      return
    end

    ImportArtistWorker.perform_async(import_artist_params[:name], current_user.id)

    redirect_to artists_path, notice: 'Your artist will be imported shortly.'
  end

  def artist_releases
    client = DiscogsRequestsService::Client.new
    artist_name = Artist.find(params['artist_id']).name
    releases = client.search_artist_releases(artist_name, max_results: import_artist_releases_params[:max_results])

    releases.each do |release|
      Release.new(
        title: release.title,
        release_type: release.type,
        year: release.year,
        discog_id: release.id,
        artist_id: params['artist_id']
      ).save
    end

    redirect_to artist_releases_url(artist_id: params['artist_id'].to_i), notice: 'Releases successfully imported.'
  end

  private

  def import_artist_params
    params.require(:import_artist).permit(
      :name
    )
  end

  def import_artist_releases_params
    params.require(:import_artist_releases).permit(
      :max_results
    )
  end
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
    def index
        @artist = Artist.find(params[:artist_id])

        @releases = @artist.releases
    end

    def show
        @artist = Artist.find(params[:artist_id])

        @release = @artist.releases.find(params[:id])
    end

    def new
        @artist = Artist.find(params[:artist_id])
        @release = Release.new(artist: @artist)
    end

    def create
        @release = Release.new(release_params)
        @artist = Artist.find(params[:artist_id])
        @release.artist = @artist

        if @release.save
            redirect_to artist_release_url(artist_id: @artist.id, id: @release.id), 
            notice: 'Created successfully'
        else
            render :new
        end
    end

    def edit
        @artist = Artist.find(params[:artist_id])
        @release = Release.find(params[:id])
        render :edit
    end
    

    def update
        @artist = Artist.find(params[:artist_id])
        @release = Release.find(params[:id])

        if @release.update(release_params)
            redirect_to artist_release_url(artist_id: @artist.id, id: @release.id),
            notice: 'Updated successfully'
        else
            render :edit
        end
    end

    def destroy
        @artist = Artist.find(params[:artist_id])
        @release = Release.find(params[:id])

        @release.destroy

        redirect_to artist_releases_url, notice: 'Release was successfully deleted'
    end

    private
    def release_params
        params.require(:release).permit(
            :title
        )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_artist.html.erb
<tr>
  <td><%= link_to artist.name, artist %></td>
  <td class="text-center">
    <%= link_to edit_artist_path(artist) do %>
      <i class="fas fa-pencil-alt"></i>
    <% end %>
    <%= link_to artist, method: :delete, data: { confirm: 'Are you sure?' } do %>
      <i class="fas fa-times"></i>
    <% end %>
  </td>
</tr>

app/views/artists/_form.html.erb
<div class="card mb-3">
  <%= form_with(model: @artist, local: true) do |form| %>
    <div class="card-body">
      <div class="row">
        <div class="col-12">
          <% if @artist.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@artist.errors.count, "error") %> prohibited
                this artist from being saved:
              </h2>
              <ul>
                <% @artist.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <label for="name" class="control-label custom-control-label">Name</label>
            <div class="input-group">
              <span class="input-group-addon"><i class="fas fa-compact-disc" aria-hidden="true"></i></span>
              <input type="text" class="form-control" id="artist-name" name="artist[name]" value="<%= @artist.name %>">
            </div>
          </div>
          <div class="form-group">
            <label for="profile" class="control-label custom-control-label">Description</label>
            <div class="input-group">
              <span class="input-group-addon"><i class="fas fa-compact-disc" aria-hidden="true"></i></span>
              <input type="text" class="form-control" id="artist-profile" name="artist[profile]" value="<%= @artist.profile %>">
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Save</button>
      </div>
    </div>
  <% end %>
</div>

app/views/artists/edit.html.erb
<%= render 'form' %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-compact-disc"></i>
    Artists
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render @artists %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="modal fade" id="importArtistModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Import Artist</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_with(url: artists_import_path, local: true) do |form| %>
        <div class="modal-body">
          <div class="card-body">
            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  <label for="name" class="control-label custom-control-label">Name</label>
                  <div class="input-group">
                    <span class="input-group-addon"><i class="fas fa-compact-disc" aria-hidden="true"></i></span>
                    <input type="text" class="form-control" id="import-artist-name" name="import_artist[name]" value="">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Import</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to(t('.new'), new_artist_path, class: "btn btn-primary btn-lg btn-block login-button") %>
<%= link_to('Import', '#', class: "btn btn-primary btn-lg btn-block login-button", 'data-toggle' => "modal", 'data-target'=>"#importArtistModal" ) %>

app/views/artists/new.html.erb
<%= render 'form' %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-compact-disc"></i>
    <%= @artist.name %>
    <%= link_to edit_artist_path(@artist) do %>
      <i class="fas fa-pencil-alt"></i>
    <% end %>
  </div>
  <div class="card-body">
    <p>Profile: <%= @artist.profile %></p>
    <p><%= link_to 'Releases', artist_releases_path(@artist) %></p>
  </div>
</div>

app/views/home/show.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="card mb-3">
      <div class="card-header">
        Card 1
      </div>
      <div class="card-body">
        Hello
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card mb-3">
      <div class="card-header">
        Card 2
      </div>
      <div class="card-body">
        World
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>GetOnRails</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('logo.png') %>
  </head>

  <body id="page-top" class="<%= current_user ? '' : 'bg-dark' %>">
    <% if current_user %>

      <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
        <%= image_tag('logo.png', size: '18', class: 'custom-logo-position') %>
        <a class="navbar-brand mr-1" href="#">GetOnRails</a>
        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
          <i class="fas fa-bars"></i>
        </button>
        <div class="ml-auto mr-0 mr-md-3 my-2 my-md-0">
        </div>
        <span style="color: white;"><%= current_user.email %></span>
        <ul class="navbar-nav ml-auto ml-md-0">
          <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user-circle fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
              <a class="dropdown-item" href="#">Configurações</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
            </div>
          </li>
        </ul>
      </nav>

      <div id="wrapper">
        <ul class="sidebar navbar-nav toggled">
          <li class="nav-item">
            <a class="nav-link" href=<%= root_path %>>
              <i class="fas fa-fw fa-home"></i>
              <span>Home</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=<%= artists_path %>>
              <i class="fas fa-fw fa-compact-disc"></i>
              <span>Artists</span>
            </a>
          </li>
        </ul>
        <div id="content-wrapper">
          <div class="container-fluid">

            <%= yield %>

          </div>
        </div>
      </div>

      <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
      </a>

      <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Vai embora?</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">Você realmente deseja sair?</div>
            <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
              <a class="btn btn-primary" href="<%= destroy_user_session_path %>" data-method="delete">Logout</a>
            </div>
          </div>
        </div>
      </div>
    <% else %>

      <%= yield %>

    <% end %>
  </body>
</html>

<script type="text/javascript">
  (function($) {
    "use strict"; // Start of use strict

    // Toggle the side navigation
    $("#sidebarToggle").on('click',function(e) {
      e.preventDefault();
      $("body").toggleClass("sidebar-toggled");
      $(".sidebar").toggleClass("toggled");
    });

    // Prevent the content wrapper from scrolling when the fixed side navigation hovered over
    $('body.fixed-nav .sidebar').on('mousewheel DOMMouseScroll wheel', function(e) {
      if ($(window).width() > 768) {
        var e0 = e.originalEvent,
          delta = e0.wheelDelta || -e0.detail;
        this.scrollTop += (delta < 0 ? 1 : -1) * 30;
        e.preventDefault();
      }
    });

    // Scroll to top button appear
    $(document).on('scroll',function() {
      var scrollDistance = $(this).scrollTop();
      if (scrollDistance > 100) {
        $('.scroll-to-top').fadeIn();
      } else {
        $('.scroll-to-top').fadeOut();
      }
    });

    // Smooth scrolling using jQuery easing
    $(document).on('click', 'a.scroll-to-top', function(event) {
      var $anchor = $(this);
      $('html, body').stop().animate({
        scrollTop: ($($anchor.attr('href')).offset().top)
      }, 1000, 'easeInOutExpo');
      event.preventDefault();
    });

  })(jQuery); // End of use strict
</script>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-compact-disc"></i>
    Records
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render @records %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<br>

<%= link_to(t('.new'), new_record_path, class: "btn btn-primary btn-lg btn-block login-button") %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-compact-disc"></i>
    <%= @record.name %>
    <%= link_to edit_record_path(@record) do %>
      <i class="fas fa-pencil-alt"></i>
    <% end %>
  </div>
  <div class="card-body">
    <p>Description: <%= @record.description %></p>
    <p>Value: <%= @record.value %></p>
  </div>
</div>

app/views/releases/edit.html.erb
<div class="card mb-3">
  <%= form_with(model: [ @artist, @release ], local: true) do |form| %>
    <div class="card-body">
      <div class="row">
        <div class="col-12">
          <% if @release.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@release.errors.count, "error") %> prohibited
                this release from being saved:
              </h2>
              <ul>
                <% @release.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <label for="title" class="control-label custom-control-label">Title</label>
            <div class="input-group">
              <span class="input-group-addon"><i class="fas fa-compact-disc" aria-hidden="true"></i></span>
              <input type="text" class="form-control" id="release-title" name="release[title]" value="<%= @release.title %>">
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Save</button>
      </div>
    </div>
  <% end %>
</div>

app/views/releases/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-compact-disc"></i>
      Releases by <%= link_to @artist.name, artist_path(@artist) %>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Title</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @releases.each do |release| %>
            <tr>
              <td><%= link_to release.title, artist_release_path(artist_id: @artist.id, id: release.id) %></td>
              <td class="text-right">
                <%= link_to edit_artist_release_path(artist_id: @artist.id, id: release.id) do %>
                  <i class="fas fa-pencil-alt"></i>
                <% end %>
                <%= link_to artist_release_path(artist_id: @artist.id, id: release.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="fas fa-times"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div>
<div class="modal fade" id="importArtistReleasesModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Import Releases</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_with(url: import_artist_releases_path, local: true) do |form| %>
        <div class="modal-body">
          <div class="card-body">
            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  <label for="name" class="control-label custom-control-label">Results</label>
                  <div class="input-group">
                    <span class="input-group-addon"><i class="fas fa-compact-disc" aria-hidden="true"></i></span>
                    <input type="text" class="form-control" id="import_artist_releases" name="import_artist_releases[max_results]" value="10">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Import</button>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to(t('.new'),
    new_artist_release_path,
    class: "btn btn-dark btn-lg btn-block login-button")
%>
<%= link_to('Import', '#', class: "btn btn-dark btn-lg btn-block login-button", 'data-toggle' => "modal", 'data-target'=>"#importArtistReleasesModal" ) %>
</div>

app/views/releases/new.html.erb
<div class="card mb-3">
  <%= form_with(model: [ @artist, @artist.releases.build ], local: true) do |form| %>
    <div class="card-body">
      <div class="row">
        <div class="col-12">
          <% if @release.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@release.errors.count, "error") %> prohibited
                this release from being saved:
              </h2>
              <ul>
                <% @release.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <label for="title" class="control-label custom-control-label">Title</label>
            <div class="input-group">
              <span class="input-group-addon"><i class="fas fa-compact-disc" aria-hidden="true"></i></span>
              <input type="text" class="form-control" id="release-title" name="release[title]" value="<%= @release.title %>">
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Save</button>
      </div>
    </div>
  <% end %>
</div>

app/views/releases/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-compact-disc"></i>
    <%= @release.title %>
  </div>
  <div class="card-body">
    <p>Year: <%= @release.year %></p>
    <p>Artist: <%= link_to @artist.name, artist_path(@artist) %></p>
  </div>
</div>